services:
  db:
    image: postgres:15
    container_name: orni-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orni_admin159
      POSTGRES_DB: orni_db
    volumes:
      - orni-db-data:/var/lib/postgresql/data
    networks:
      - orni-network

  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    container_name: orni-backend
    depends_on:
      - db
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgres:orni_admin159@db:5432/orni_db
      JWT_ACCESS_SECRET: 1585395257
      JWT_REFRESH_SECRET: TestRefresh153
      JWT_ACCESS_EXPIRATION: 15m
      JWT_REFRESH_EXPIRATION: 7d
    networks:
      - orni-network

volumes:
  orni-db-data:

networks:
  orni-network:
    driver: bridge
